# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The base box to use
  config.vm.box = "joshbeard/windows_2008_r2"

  # forwards port 8080 on the host to port 80 on the guest
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Enables Guest RDP without clashes to the Host RDP port
  config.vm.network "forwarded_port", guest: 3389, host: 33389
  
  # Limit the Guest RAM to 1GB
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end
  
  # enable Chef
  config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = 'provision/cookbooks'
      chef.add_recipe 'web_example'
  end

end
